" ~/.vimrc - Configuración de vim
" Semana 4: Editores y Dotfiles

" ---- Básico ----
set nocompatible
syntax on
set encoding=utf-8

" ---- Apariencia ----
set number
set cursorline
set showmode
set ruler
set laststatus=2

" ---- Indentación ----
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
set smartindent

" ---- Búsqueda ----
set incsearch
set hlsearch
set ignorecase
set smartcase

" ---- Comportamiento ----
set backspace=indent,eol,start
set wrap
set linebreak
set scrolloff=5
set wildmenu

" ---- Archivos ----
set nobackup
set noswapfile

" ---- Mapeos personalizados ----
inoremap jj <Esc>

nnoremap <C-s> :w<CR>
inoremap <C-s> <Esc>:w<CR>a

nnoremap <Esc> :nohlsearch<CR>

nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
